replicaCount: 3

image:
  repository: sbika/serverabdelli
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4000

env:
  - name: MONGO_URI
    value: mongodb://hamma:hamma@mongoAbdelli:27017/abdellino?authSource=admin
  - name: PORT
    value: "4000"

ingress:
  enabled: false

# Ajout de la section ServiceAccount
serviceAccount:
  create: true  # Créer le ServiceAccount

# Ajout de la section Autoscaling
autoscaling:
  enabled: true  # Activer l'auto-scaling (ou mettre false si vous ne voulez pas l'activer)
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
