replicaCount: 3

image:
  repository: sbika/clientabdelli
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5173

env:
  - name: REACT_APP_SERVER_URL
    value: http://server-service:4000

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: mern-app.local
      paths:
        - path: /
          pathType: Prefix  # Utilisez "Prefix" pour une gestion correcte des chemins
  tls: []
  
# Ajout de la configuration pour le service account
serviceAccount:
  create: true  # Créez un service account si nécessaire
  name: ""  # Si vous ne voulez pas spécifier un nom spécifique, laissez vide.
