apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9216"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: mongodb-exporter
  ports:
  - protocol: TCP
    port: 9216
    targetPort: 9216
  type: ClusterIP
