apiVersion: v1
kind: Service
metadata:
  name: node-exporter-service
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
    prometheus.io/path: "/metrics"
spec:
  ports:
    - port: 9100
      targetPort: 9100
  selector:
    app: node-exporter
  type: ClusterIP
