apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api-abdelli
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-abdelli
  template:
    metadata:
      labels:
        app: api-abdelli
      annotations:
        prometheus.io/scrape: "true"      # Activer le scraping pour ce service
        prometheus.io/port: "4000"       # Port d'exposition des métriques
        prometheus.io/path: "/metrics"  # Chemin des métriques
    spec:
      containers:
      - name: api-abdelli
        image: sbika/serverabdelli:latest
        ports:
        - containerPort: 4000
        envFrom:
        - configMapRef:
            name: app-configmap
