apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: api-abdelli
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
    nodePort: 30001
  type: NodePort
