apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  MONGO_URI: "mongodb://hamma:hamma@mongoAbdelli:27017/abdellino?authSource=admin"
  PORT: "4000"
  REACT_APP_SERVER_URL: "http://server-service:4000"
