apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: webAbdelli
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-abdelli
  template:
    metadata:
      labels:
        app: web-abdelli
    spec:
      containers:
      - name: web-abdelli
        image: sbika/clientabdelli:latest
        ports:
        - containerPort: 5173
