apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: web-abdelli
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-abdelli
  template:
    metadata:
      labels:
        app: web-abdelli
      annotations:
        prometheus.io/scrape: "true"      # Activer le scraping
        prometheus.io/port: "5173"       # Port pour les métriques
        prometheus.io/path: "/metrics"  # Chemin des métriques
    spec:
      containers:
      - name: web-abdelli
        image: sbika/clientabdelli:latest
        ports:
        - containerPort: 5173
