apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo-abdelli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-abdelli
  template:
    metadata:
      labels:
        app: mongo-abdelli
      annotations:
        prometheus.io/scrape: "true"      # Activer le scraping
        prometheus.io/port: "9216"       # Port exposé par MongoDB Exporter
        prometheus.io/path: "/metrics"  # Chemin des métriques
    spec:
      containers:
      - name: mongo-abdelli
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "hamma"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "hamma"
      - name: mongodb-exporter
        image: bitnami/mongodb-exporter:latest
        ports:
        - containerPort: 9216
        env:
        - name: MONGODB_URI
          value: "mongodb://hamma:hamma@localhost:27017"
