apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo-abdelli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-abdelli
  template:
    metadata:
      labels:
        app: mongo-abdelli
    spec:
      containers:
      - name: mongo-abdelli
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "hamma"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "hamma"
